const $=id=>document.getElementById(id);let originalGray=null;
function createSample(){const w=900,h=650;const c=$("originalCanvas"),x=c.getContext("2d");c.width=w;c.height=h;x.fillStyle="#fff";x.fillRect(0,0,w,h);x.fillStyle="#111";x.textAlign="center";x.font="bold 34px Georgia";x.fillText("IMAGE PROCESSING",w/2,60);x.textAlign="left";x.font="bold 20px Georgia";[["1. Introduction",120],["2. Digital Image",275],["3. Types of Noise",430]].forEach(a=>x.fillText(a[0],60,a[1]));x.font="17px Georgia";[["Image processing performs operations on an image to obtain",150],["an enhanced image or useful information from its content.",176],["Digital images are represented as arrays of pixels and are",305],["used in document analysis, recognition and many applications.",331],["Salt-and-Pepper Noise appears as random black and white pixels.",460],["Median filtering is useful for removing this impulse noise.",486],["The objective is to restore documents while preserving text.",512]].forEach(a=>x.fillText(a[0],80,a[1]));x.font="15px Georgia";x.fillText("This project demonstrates median filters of 3×3, 5×5 and 7×7.",80,565);originalGray=toGray(x.getImageData(0,0,w,h).data,w,h)}
function toGray(d,w,h){const g=new Uint8ClampedArray(w*h);for(let i=0,p=0;i<d.length;i+=4,p++)g[p]=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);return g}
function loadFile(file){const im=new Image();im.onload=()=>{const max=1100,s=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.round(im.naturalWidth*s),h=Math.round(im.naturalHeight*s),c=$("originalCanvas"),x=c.getContext("2d");c.width=w;c.height=h;x.drawImage(im,0,0,w,h);originalGray=toGray(x.getImageData(0,0,w,h).data,w,h);process();$("status").textContent=`Loaded: ${file.name}`};im.src=URL.createObjectURL(file)}
function noise(g,d){const n=new Uint8ClampedArray(g),count=Math.floor(g.length*d);let seed=123456789;const r=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};for(let i=0;i<count;i++)n[Math.floor(r()*n.length)]=i%2?255:0;return n}
function median(a,w,h,k){const out=new Uint8ClampedArray(a.length),r=(k/2)|0,v=new Array(k*k);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let n=0;for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const yy=Math.max(0,Math.min(h-1,y+dy)),xx=Math.max(0,Math.min(w-1,x+dx));v[n++]=a[yy*w+xx]}v.sort((a,b)=>a-b);out[y*w+x]=v[(n/2)|0]}return out}
function draw(g,c,w,h){c.width=w;c.height=h;const x=c.getContext("2d"),o=x.createImageData(w,h);for(let i=0,p=0;i<g.length;i++,p+=4)o.data[p]=o.data[p+1]=o.data[p+2]=g[i],o.data[p+3]=255;x.putImageData(o,0,0)}
function mse(a,b){let s=0;for(let i=0;i<a.length;i++){const d=a[i]-b[i];s+=d*d}return s/a.length}function psnr(m){return m===0?Infinity:10*Math.log10(65025/m)}
function hist(a,b){const c=$("histCanvas"),x=c.getContext("2d"),w=Math.max(500,c.clientWidth||800),h=280,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);const A=new Array(256).fill(0),B=new Array(256).fill(0);a.forEach(v=>A[v]++);b.forEach(v=>B[v]++);const mx=Math.max(...A,...B,1),x0=45,y0=235,pw=w-60,ph=210;x.strokeStyle="#ddd7ca";for(let j=0;j<5;j++){const y=y0-j*ph/4;x.beginPath();x.moveTo(x0,y);x.lineTo(w-15,y);x.stroke()}function line(z,col){x.strokeStyle=col;x.lineWidth=1.5;x.beginPath();z.forEach((v,i)=>{const xx=x0+i/255*pw,yy=y0-v/mx*ph;i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()}line(A,"#75695d");line(B,"#a95535");x.fillStyle="#666";x.font="12px Arial";x.fillText("0",42,253);x.fillText("50",x0+pw*50/255-8,253);x.fillText("100",x0+pw*100/255-10,253);x.fillText("150",x0+pw*150/255-10,253);x.fillText("200",x0+pw*200/255-10,253);x.fillText("255",w-29,253);x.fillText("Pixel Intensity",w/2-38,273)}
function process(){if(!originalGray)createSample();const w=$("originalCanvas").width,h=$("originalCanvas").height,d=+$('noiseSlider').value/100,k=+$('kernelSelect').value,n=noise(originalGray,d),f=median(n,w,h,k),m=mse(originalGray,f),p=psnr(m);draw(originalGray,$("originalCanvas"),w,h);draw(n,$("noisyCanvas"),w,h);draw(f,$("filteredCanvas"),w,h);$("mse").textContent=m.toFixed(2);$("psnr").textContent=Number.isFinite(p)?p.toFixed(2)+" dB":"∞";$("metricNoise").textContent=(d*100).toFixed(0)+"%";$("metricKernel").textContent=`${k}×${k}`;$("noiseValue").textContent=(d*100).toFixed(0)+"%";$("filteredTitle").textContent=`Median Filter · ${k}×${k}`;$("status").textContent=`Processed • ${w}×${h} pixels • ${k}×${k} filter • ${(d*100).toFixed(0)}% noise`;hist(n,f)}
$("fileInput").addEventListener("change",e=>e.target.files[0]&&loadFile(e.target.files[0]));$("sampleBtn").onclick=()=>{createSample();process();$("status").textContent="Sample document loaded."};$("processBtn").onclick=process;$("noiseSlider").oninput=()=>{$("noiseValue").textContent=$("noiseSlider").value+"%"};$("kernelSelect").onchange=()=>{process()};createSample();process();
